export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const SET_ANSWER = "SET_ANSWER";
export const RESET_QUIZ = "RESET_QUIZ";
export const UPDATE_SCORE = "UPDATE_SCORE";
export const SET_CATEGORY = "SET_CATEGORY";
export const SET_DIFFICULTY = "SET_DIFFICULTY";